### ISSUE TITLE
[BUG] 使用 Nginx 将面板反代为 https 时, 无法正确生成 OAuth 的 回调 url 协议部分

### ISSUE THREAD

**Issue by MemoryShadow** [nezhahq/nezha#1000]
### 运行环境

Ubuntu GNU/Linux 22.04.1-aarch64

### Nezha 版本

v1.7.5 (Docker)

### 描述问题

使用 Nginx 将 Docker 安装的面板反代为 https 时, 无法正确生成 OAuth 的 回调 url 协议部分. 发送的回调地址永远为 http.

如果使用 Cloudflare 的代理, 即便不按照 [Dashboard 反向代理配置](https://nezha.wiki/guide/q3.html) 的指示进行修改依然能够正常工作.

### 复现步骤

1. 使用 [安装 Dashboard](https://nezha.wiki/guide/dashboard.html) 中提供的安装脚本进行安装, 安装模式为 Docker, 选择启用 tls:
> curl -L https://raw.githubusercontent.com/nezhahq/scripts/refs/heads/main/install.sh -o nezha.sh && chmod +x nezha.sh && sudo ./nezha.sh
2. 按照 [Dashboard 反向代理配置](https://nezha.wiki/guide/q3.html) 的指示进行修改, 修改后的 Nginx 配置将放在后面 "配置信息" 自然段
3. 编辑 `/opt/nezha/dashboard/data/config.yaml` 添加 OAuth 段落相关信息, , 修改后的 NeZha 配置将放在后面 "配置信息" 
4. 使用 `cd /opt/nezha/dashboard/; docker compose down && docker compose up -d` 重启 Nezha 并清空之前控制台的日志.
5. 登陆 NeZha, 尝试绑定 OAuth, 在`https://nezha.host.domain/api/v1/oauth2/callback?...`得到 `{"error":"oauth2: \"invalid_grant\" \"Code not valid\""}`
6. 登陆 OAuth 服务后台, 发现原因如下
> Parameter 'redirect_uri' did not match originally saved redirect URI used in initial OIDC request. Saved redirectUri: https://nezha.host.domain/api/v1/oauth2/callback, redirectUri parameter: http://nezha.host.domain/api/v1/oauth2/callback
7. 遂得出结论, 由于 redirectUri 在获得 code 向 OAuth 请求 Token 时将 redirectUri 的协议部分拼为了 http 导致无法正确取得 Token.

### 配置信息

NeZha Config:
```yaml
debug: true
realipheader: ""
language: zh_CN
sitename: [...]
usertemplate: user-dist
admintemplate: admin-dist
jwtsecretkey: [...]
listenport: 8100
listenhost: ""
installhost: nezha.host.domain:443
tls: true
location: Asia/Shanghai
forceauth: false
enableplainipinnotification: false
enableipchangenotification: false
ipchangenotificationgroupid: 0
cover: 1
ignoredipnotification: ""
ignoredipnotificationserverids: {}
avgpingcount: 2
dnsservers: ""
customcode: ""
customcodedashboard: ""
oauth2:
  OAuth Service:
    clientid: "[...]"
    clientsecret: "[...]"
    endpoint:
      authurl: "https://auth.host.domain/auth"
      tokenurl: "https://auth.host.domain/token"
    scopes:
      - openid
      - profile
    userinfourl: "https://auth.host.domain/userinfo"
    useridpath: "sub"

```
Nginx Config:
```conf
server {
  listen       80;
  listen       [::]:80;
  server_name   nezha.host.domain;
  client_max_body_size 50m;
  #proxy_set_header X-Real-IP $remote_addr;
  #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  return 301 https://$host$request_uri;
}

server {
  listen        443 ssl;
  listen        [::]:443 ssl;
  http2 on;
  server_name   nezha.host.domain;
  ssl_certificate       "/home/Web/.ssl/host.domain.pem";
  ssl_certificate_key   "/home/Web/.ssl/host.domain.key";
  ssl_stapling on;
  ssl_session_timeout   1d;
  ssl_session_cache     shared:SSL:1m;
  ssl_protocols TLSv1.2 TLSv1.3;

  underscores_in_headers on;
  proxy_set_header X-Forwarded-Proto https; #抵达此处时, 无论如何都应该为 https
  #set_real_ip_from 172.245.48.0/20;   # CF
  #real_ip_header CF-Connecting-IP;    # CF
  real_ip_header X-Forwarded-For;
  #ssl_ciphers          PROFILE=SYSTEM;
  #ssl_prefer_server_ciphers    on;
  #client_max_body_size 50m;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  # grpc 相关
  location ^~ /proto.NezhaService/ {
    grpc_set_header Host $host;
    #grpc_set_header nz-realip $http_CF_Connecting_IP; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
    grpc_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
    grpc_read_timeout 600s;
    grpc_send_timeout 600s;
    grpc_socket_keepalive on;
    client_max_body_size 10m;
    grpc_buffer_size 4m;
    grpc_pass grpc://dashboard;
  }
  # websocket 相关
  location ~* ^/api/v1/ws/(server|terminal|file)(.*)$ {
    proxy_set_header Host $host;
    #proxy_set_header nz-realip $http_cf_connecting_ip; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
    proxy_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
    proxy_set_header Origin https://$host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_pass http://127.0.0.1:8008;
  }

  location / {
    proxy_set_header Host $host;
    #proxy_set_header nz-realip $http_cf_connecting_ip; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
    proxy_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_max_temp_file_size 0;
    proxy_pass http://127.0.0.1:8008;
  }
}

upstream dashboard {
  server 127.0.0.1:8008;
  keepalive 512;
}
```

### 附加信息

我一路追踪到了 [这一行](https://github.com/nezhahq/nezha/blob/master/cmd/dashboard/controller/oauth2.go#L26) 可能是这里的问题.

> if forwardedProto := c.Request.Header.Get("X-Forwarded-Proto"); forwardedProto == "https" || strings.HasPrefix(referer, "https://") {

我按照代码逻辑在 Nginx 中设置了 X-Forwarded-Proto 为 https, 并重写了 请求头中的 Request 字段为 https:// 开头, 依然无效.

### 验证

- [x] 我确认这是一个 nezha (哪吒面板) 的问题。
- [x] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。
