### ISSUE TITLE
OAuth 2.0 绑定时程序崩溃

### ISSUE THREAD

**Issue by liununu** [nezhahq/nezha#1007]
### 运行环境

Debian - 12.9 x86_64

### Nezha 版本

1.8.0

### 描述问题

<details>

1. Dashboard 使用的 Cloudflare tunnel 访问，服务器上使用 nginx 进行反代

2. 尝试通过 Github 和 Cloudflare access 绑定时，最后在 redirect callback `https://<domain-name>/api/v1/oauth2/callback?code=<code>&state=<state>` 都会出现 502 错误

3. 通过 `journalctl -u nezha-dashboard -f` 观察，发现程序崩溃并重启了

</details>

### 复现步骤

<details></details>

### 配置信息

<details>

崩溃日志：[crash.log](https://github.com/user-attachments/files/18938389/crash.log)

Oauth 2.0 配置参照：https://nezha.wiki/guide/q14.html#cloudflare-access 
```yaml
oauth2:
  Cloudflare:
    clientid: "<my-client-id>"
    clientsecret: "<my-client-secret>"
    endpoint:
      authurl: "https://<my-namespace>.cloudflareaccess.com/cdn-cgi/access/sso/oidc/<my-client-id>/authorization"
      tokenurl: "https://<my-namespace>.cloudflareaccess.com/cdn-cgi/access/sso/oidc/<my-client-id>/token"
    scopes:
      - openid
      - profile
    userinfourl: "https://<my-namespace>.cloudflareaccess.com/cdn-cgi/access/sso/oidc/<my-client-id>/userinfo"
    useridpath: "sub"
```

NGINX
```
server {
    listen 8100;
    http2 on;
    server_name _;

    underscores_in_headers on;
    set_real_ip_from 0.0.0.0/0;
    real_ip_header CF-Connecting-IP;

    keepalive_time 24h;
    keepalive_requests 100000;
    keepalive_timeout 120s;
    # grpc
    location ^~ /proto.NezhaService/ {
        grpc_set_header Host $host;
        grpc_set_header nz-realip $http_cf_connecting_ip;
        grpc_read_timeout 600s;
        grpc_send_timeout 600s;
        grpc_socket_keepalive on;
        client_max_body_size 10m;
        grpc_buffer_size 4m;
        grpc_pass grpc://127.0.0.1:8008;
    }
    # websocket
    location ~* ^/api/v1/ws/(server|terminal|file)(.*)$ {
        proxy_set_header Host $host;
        proxy_set_header nz-realip $http_cf_connecting_ip;
        proxy_set_header Origin https://$host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://127.0.0.1:8008;
    }
    # web
    location / {
        proxy_set_header Host $host;
        proxy_set_header nz-realip $http_cf_connecting_ip;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_max_temp_file_size 0;
        proxy_pass http://127.0.0.1:8008;
    }
}
```

</details>

### 附加信息

<details></details>

### 验证

- [x] 我确认这是一个 nezha (哪吒面板) 的问题。
- [x] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。
