### ISSUE TITLE
后台提示错误ServerProvider Error，并且面板无法显示添加的小鸡

### ISSUE THREAD

**Issue by ericdai-dev** [nezhahq/nezha#896]
### Environment

Debian 11

### Nezha Version

1.3.0

### Describe the bug

<details>
ServerProvider Error

Cannot read properties of undefined (reading 'map')
</details>

### To Reproduce

<details></details>

### Additional Context

<details></details>

### Validation

- [X] I confirm this is a bug about nezha (Nezha Dashboard).
- [X] I have searched Issues and confirm this bug has been reported before.

**Comment by CoderConan** [comment]
I'm having the same issue

https://github.com/user-attachments/assets/c9138ab8-5a6a-46ea-93e0-6e87f1ec3386

**Comment by fz0000** [comment]
Same issue on Ubuntu 22.04.5 LTS

Please see attached output for my choices during  installation:

<details><summary>Details</summary>
<p>

```
root@nezha:~# ./nezha.sh 
根据geoip api提供的信息，当前IP可能在中国
否选用中国镜像完成安装? [Y/n] (自定义镜像输入 3)：Y
使用中国镜像
请自行选择您的安装方式：
1. Docker
2. 独立安装
请输入选择 [1-2]：2
哪吒监控管理脚本
--- https://github.com/nezhahq/nezha ---
1.  安装面板端
2.  修改面板配置
3.  重启并更新面板
4.  查看面板日志
5.  卸载管理面板
————————————————-
6.  更新脚本
————————————————-
0.  退出脚本

请输入选择 [0-6]: 1
> 安装
> 修改配置
请输入站点标题: MySite
请输入暴露端口: (默认 8008)8008
请指定安装命令中预设的 nezha-agent 连接地址 （例如 example.com:443）nezha.mydomain.com:8009
是否希望通过 TLS 连接 Agent？（影响安装命令）[y/N]N
请指定后台语言
1. 中文（简体）
2. 中文（台灣）
3. English
请输入选项 [1-3]1
正在下载服务文件
Dashboard 配置 修改成功，请稍等 Dashboard 重启生效
> 重启并更新
当前最新版本为： v1.4.4
Created symlink /etc/systemd/system/multi-user.target.wants/nezha-dashboard.service -> /etc/systemd/system/nezha-dashboard.service.
哪吒监控 重启成功
默认地址：域名:站点访问端口

* 按回车返回主菜单 *
``` 

</p>
</details> 

And the content of `/opt/nezha/dashboard/data/config.yaml`:
<details><summary>Details</summary>
<p>

```yaml
debug: false
realipheader: ""
language: zh_CN
sitename: MySite
usertemplate: user-dist
admintemplate: admin-dist
jwtsecretkey: --hidden--
agentsecretkey: --hidden--
listenport: 8008
listenhost: ""
installhost: nezha.mydomain.com:8009
tls: false
location: Asia/Shanghai
enableplainipinnotification: false
enableipchangenotification: false
ipchangenotificationgroupid: 0
cover: 1
ignoredipnotification: ""
ignoredipnotificationserverids: {}
avgpingcount: 2
dnsservers: ""
customcode: ""
customcodedashboard: ""
``` 

</p>
</details>

**Comment by syouko** [comment]
一样的故障。
Debian12 docker安装，非8008端口，进入后台管理界面-个人信息，就会弹。
不影响安装agent，安装完成后再进入个人信息就没报错了

**Comment by jin-gubang** [comment]
强制刷新就会没有这个错误了

**Comment by wc7086** [comment]
我用雷池反代也遇到了同样的问题，日志可以看到已经接收到小鸡的POST请求。

**Comment by SHLE1** [comment]
出现这个问题要把`请指定安装命令中预设的 nezha-agent 连接地址`设置为本机的安装端口(ip:8008)，并且安装完agent以后就会正常了

**Comment by fz0000** [comment]
I reviewed the [user guide](https://nezha.wiki/en_US/guide/q3.html), which states that Dashboard and gRPC share the same `8008` port. Therefore, I update all ports in the config files to `8080`, but it's still failed.

Then I tried to change the server in agent config file from `nezha.mydomain.com` to IP address `192.168.x.x` , and it works well now:

`/opt/nezha/dashboard/data/config.yaml` on server:
<details><summary>Details</summary>
<p>

```yml
debug: false
realipheader: ""
language: zh_CN
sitename: MySite
usertemplate: user-dist
admintemplate: admin-dist
jwtsecretkey: --hidden--
agentsecretkey: --hidden--
listenport: 8008
listenhost: ""
installhost: nezha.mydomain.com:8008
tls: false
location: Asia/Shanghai
enableplainipinnotification: false
enableipchangenotification: false
ipchangenotificationgroupid: 0
cover: 1
ignoredipnotification: ""
ignoredipnotificationserverids: {}
avgpingcount: 2
dnsservers: ""
customcode: ""
customcodedashboard: ""
oauth2: {}
``` 

</p>
</details> 

`/opt/nezha/agent/config.yml` on agent:
<details><summary>Details</summary>
<p>

```yml
client_secret: --hidden--
debug: false
disable_auto_update: false
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 3
self_update_period: 0
server: 192.168.1.10:8008
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: --hidden--
``` 

</p>
</details> 

I'm not sure if it is a bug. But you can try it as a workaround if you encounter the same problem.

Environment:
- Nezha Version: 1.5.2
- Agent Version: 1.5.0
